version: '2.4'

services:
  server:
    image: zeppelin-cpu
    #runtime: nvidia
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
      MASTER: local[*]
      #NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 8080:8080
    volumes:
      - ./notebooks:/zeppelin/notebook
      - ./data:/data
      - ./images:/images
      - ./.aws:/root/.aws

